### ISSUE TITLE
add a "update_url" to "playerlist.json"

### ISSUE THREAD

**Issue by bobkinect98** [MonkoTubeYT/tf2bd-lozarthsrules#1]
rules.json has one, so you can probably also have a updater on playerlist.json too
something like
`"update_url": "https://github.com/MonkoTubeYT/tf2bd-lozarthsrules/raw/main/playerlist.json"`

**Comment by MonkoTubeYT** [comment]
I added one earlier, I think it might overwrite players that were marked by you though.
